// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mq_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mq_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mq_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mq_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mq_5fmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mq_5fmsg_2eproto;
namespace RabbitMQ {
class BasicProperties;
class BasicPropertiesDefaultTypeInternal;
extern BasicPropertiesDefaultTypeInternal _BasicProperties_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Message_Payload;
class Message_PayloadDefaultTypeInternal;
extern Message_PayloadDefaultTypeInternal _Message_Payload_default_instance_;
}  // namespace RabbitMQ
PROTOBUF_NAMESPACE_OPEN
template<> ::RabbitMQ::BasicProperties* Arena::CreateMaybeMessage<::RabbitMQ::BasicProperties>(Arena*);
template<> ::RabbitMQ::Message* Arena::CreateMaybeMessage<::RabbitMQ::Message>(Arena*);
template<> ::RabbitMQ::Message_Payload* Arena::CreateMaybeMessage<::RabbitMQ::Message_Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace RabbitMQ {

enum ExchangeType : int {
  UNKNOWNTYPE = 0,
  DIRECT = 1,
  FANOUT = 2,
  TOPIC = 3,
  ExchangeType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ExchangeType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ExchangeType_IsValid(int value);
constexpr ExchangeType ExchangeType_MIN = UNKNOWNTYPE;
constexpr ExchangeType ExchangeType_MAX = TOPIC;
constexpr int ExchangeType_ARRAYSIZE = ExchangeType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ExchangeType_descriptor();
template<typename T>
inline const std::string& ExchangeType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ExchangeType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ExchangeType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ExchangeType_descriptor(), enum_t_value);
}
inline bool ExchangeType_Parse(
    const std::string& name, ExchangeType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ExchangeType>(
    ExchangeType_descriptor(), name, value);
}
enum DeliveryMode : int {
  UNKNOWNMODE = 0,
  UNDURABLE = 1,
  DURABLE = 2,
  DeliveryMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DeliveryMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool DeliveryMode_IsValid(int value);
constexpr DeliveryMode DeliveryMode_MIN = UNKNOWNMODE;
constexpr DeliveryMode DeliveryMode_MAX = DURABLE;
constexpr int DeliveryMode_ARRAYSIZE = DeliveryMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DeliveryMode_descriptor();
template<typename T>
inline const std::string& DeliveryMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DeliveryMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DeliveryMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DeliveryMode_descriptor(), enum_t_value);
}
inline bool DeliveryMode_Parse(
    const std::string& name, DeliveryMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DeliveryMode>(
    DeliveryMode_descriptor(), name, value);
}
// ===================================================================

class BasicProperties :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RabbitMQ.BasicProperties) */ {
 public:
  BasicProperties();
  virtual ~BasicProperties();

  BasicProperties(const BasicProperties& from);
  BasicProperties(BasicProperties&& from) noexcept
    : BasicProperties() {
    *this = ::std::move(from);
  }

  inline BasicProperties& operator=(const BasicProperties& from) {
    CopyFrom(from);
    return *this;
  }
  inline BasicProperties& operator=(BasicProperties&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BasicProperties& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BasicProperties* internal_default_instance() {
    return reinterpret_cast<const BasicProperties*>(
               &_BasicProperties_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BasicProperties& a, BasicProperties& b) {
    a.Swap(&b);
  }
  inline void Swap(BasicProperties* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BasicProperties* New() const final {
    return CreateMaybeMessage<BasicProperties>(nullptr);
  }

  BasicProperties* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BasicProperties>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BasicProperties& from);
  void MergeFrom(const BasicProperties& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BasicProperties* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RabbitMQ.BasicProperties";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mq_5fmsg_2eproto);
    return ::descriptor_table_mq_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kRoutingKeyFieldNumber = 3,
    kDeliveryModeFieldNumber = 2,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string routing_key = 3;
  void clear_routing_key();
  const std::string& routing_key() const;
  void set_routing_key(const std::string& value);
  void set_routing_key(std::string&& value);
  void set_routing_key(const char* value);
  void set_routing_key(const char* value, size_t size);
  std::string* mutable_routing_key();
  std::string* release_routing_key();
  void set_allocated_routing_key(std::string* routing_key);
  private:
  const std::string& _internal_routing_key() const;
  void _internal_set_routing_key(const std::string& value);
  std::string* _internal_mutable_routing_key();
  public:

  // .RabbitMQ.DeliveryMode delivery_mode = 2;
  void clear_delivery_mode();
  ::RabbitMQ::DeliveryMode delivery_mode() const;
  void set_delivery_mode(::RabbitMQ::DeliveryMode value);
  private:
  ::RabbitMQ::DeliveryMode _internal_delivery_mode() const;
  void _internal_set_delivery_mode(::RabbitMQ::DeliveryMode value);
  public:

  // @@protoc_insertion_point(class_scope:RabbitMQ.BasicProperties)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr routing_key_;
  int delivery_mode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mq_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class Message_Payload :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RabbitMQ.Message.Payload) */ {
 public:
  Message_Payload();
  virtual ~Message_Payload();

  Message_Payload(const Message_Payload& from);
  Message_Payload(Message_Payload&& from) noexcept
    : Message_Payload() {
    *this = ::std::move(from);
  }

  inline Message_Payload& operator=(const Message_Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message_Payload& operator=(Message_Payload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message_Payload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message_Payload* internal_default_instance() {
    return reinterpret_cast<const Message_Payload*>(
               &_Message_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Message_Payload& a, Message_Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Message_Payload* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message_Payload* New() const final {
    return CreateMaybeMessage<Message_Payload>(nullptr);
  }

  Message_Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message_Payload>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message_Payload& from);
  void MergeFrom(const Message_Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message_Payload* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RabbitMQ.Message.Payload";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mq_5fmsg_2eproto);
    return ::descriptor_table_mq_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBodyFieldNumber = 2,
    kPropertiesFieldNumber = 1,
  };
  // string body = 2;
  void clear_body();
  const std::string& body() const;
  void set_body(const std::string& value);
  void set_body(std::string&& value);
  void set_body(const char* value);
  void set_body(const char* value, size_t size);
  std::string* mutable_body();
  std::string* release_body();
  void set_allocated_body(std::string* body);
  private:
  const std::string& _internal_body() const;
  void _internal_set_body(const std::string& value);
  std::string* _internal_mutable_body();
  public:

  // .RabbitMQ.BasicProperties properties = 1;
  bool has_properties() const;
  private:
  bool _internal_has_properties() const;
  public:
  void clear_properties();
  const ::RabbitMQ::BasicProperties& properties() const;
  ::RabbitMQ::BasicProperties* release_properties();
  ::RabbitMQ::BasicProperties* mutable_properties();
  void set_allocated_properties(::RabbitMQ::BasicProperties* properties);
  private:
  const ::RabbitMQ::BasicProperties& _internal_properties() const;
  ::RabbitMQ::BasicProperties* _internal_mutable_properties();
  public:

  // @@protoc_insertion_point(class_scope:RabbitMQ.Message.Payload)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_;
  ::RabbitMQ::BasicProperties* properties_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mq_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class Message :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RabbitMQ.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RabbitMQ.Message";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_mq_5fmsg_2eproto);
    return ::descriptor_table_mq_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Message_Payload Payload;

  // accessors -------------------------------------------------------

  enum : int {
    kValidFieldNumber = 4,
    kPayloadFieldNumber = 1,
    kOffsetFieldNumber = 2,
    kLengthFieldNumber = 3,
  };
  // string valid = 4;
  void clear_valid();
  const std::string& valid() const;
  void set_valid(const std::string& value);
  void set_valid(std::string&& value);
  void set_valid(const char* value);
  void set_valid(const char* value, size_t size);
  std::string* mutable_valid();
  std::string* release_valid();
  void set_allocated_valid(std::string* valid);
  private:
  const std::string& _internal_valid() const;
  void _internal_set_valid(const std::string& value);
  std::string* _internal_mutable_valid();
  public:

  // .RabbitMQ.Message.Payload payload = 1;
  bool has_payload() const;
  private:
  bool _internal_has_payload() const;
  public:
  void clear_payload();
  const ::RabbitMQ::Message_Payload& payload() const;
  ::RabbitMQ::Message_Payload* release_payload();
  ::RabbitMQ::Message_Payload* mutable_payload();
  void set_allocated_payload(::RabbitMQ::Message_Payload* payload);
  private:
  const ::RabbitMQ::Message_Payload& _internal_payload() const;
  ::RabbitMQ::Message_Payload* _internal_mutable_payload();
  public:

  // uint32 offset = 2;
  void clear_offset();
  ::PROTOBUF_NAMESPACE_ID::uint32 offset() const;
  void set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_offset() const;
  void _internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 length = 3;
  void clear_length();
  ::PROTOBUF_NAMESPACE_ID::uint32 length() const;
  void set_length(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_length() const;
  void _internal_set_length(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:RabbitMQ.Message)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr valid_;
  ::RabbitMQ::Message_Payload* payload_;
  ::PROTOBUF_NAMESPACE_ID::uint32 offset_;
  ::PROTOBUF_NAMESPACE_ID::uint32 length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_mq_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BasicProperties

// string id = 1;
inline void BasicProperties::clear_id() {
  id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& BasicProperties::id() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.BasicProperties.id)
  return _internal_id();
}
inline void BasicProperties::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.BasicProperties.id)
}
inline std::string* BasicProperties::mutable_id() {
  // @@protoc_insertion_point(field_mutable:RabbitMQ.BasicProperties.id)
  return _internal_mutable_id();
}
inline const std::string& BasicProperties::_internal_id() const {
  return id_.GetNoArena();
}
inline void BasicProperties::_internal_set_id(const std::string& value) {
  
  id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void BasicProperties::set_id(std::string&& value) {
  
  id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RabbitMQ.BasicProperties.id)
}
inline void BasicProperties::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RabbitMQ.BasicProperties.id)
}
inline void BasicProperties::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RabbitMQ.BasicProperties.id)
}
inline std::string* BasicProperties::_internal_mutable_id() {
  
  return id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* BasicProperties::release_id() {
  // @@protoc_insertion_point(field_release:RabbitMQ.BasicProperties.id)
  
  return id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void BasicProperties::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:RabbitMQ.BasicProperties.id)
}

// .RabbitMQ.DeliveryMode delivery_mode = 2;
inline void BasicProperties::clear_delivery_mode() {
  delivery_mode_ = 0;
}
inline ::RabbitMQ::DeliveryMode BasicProperties::_internal_delivery_mode() const {
  return static_cast< ::RabbitMQ::DeliveryMode >(delivery_mode_);
}
inline ::RabbitMQ::DeliveryMode BasicProperties::delivery_mode() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.BasicProperties.delivery_mode)
  return _internal_delivery_mode();
}
inline void BasicProperties::_internal_set_delivery_mode(::RabbitMQ::DeliveryMode value) {
  
  delivery_mode_ = value;
}
inline void BasicProperties::set_delivery_mode(::RabbitMQ::DeliveryMode value) {
  _internal_set_delivery_mode(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.BasicProperties.delivery_mode)
}

// string routing_key = 3;
inline void BasicProperties::clear_routing_key() {
  routing_key_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& BasicProperties::routing_key() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.BasicProperties.routing_key)
  return _internal_routing_key();
}
inline void BasicProperties::set_routing_key(const std::string& value) {
  _internal_set_routing_key(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.BasicProperties.routing_key)
}
inline std::string* BasicProperties::mutable_routing_key() {
  // @@protoc_insertion_point(field_mutable:RabbitMQ.BasicProperties.routing_key)
  return _internal_mutable_routing_key();
}
inline const std::string& BasicProperties::_internal_routing_key() const {
  return routing_key_.GetNoArena();
}
inline void BasicProperties::_internal_set_routing_key(const std::string& value) {
  
  routing_key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void BasicProperties::set_routing_key(std::string&& value) {
  
  routing_key_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RabbitMQ.BasicProperties.routing_key)
}
inline void BasicProperties::set_routing_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  routing_key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RabbitMQ.BasicProperties.routing_key)
}
inline void BasicProperties::set_routing_key(const char* value, size_t size) {
  
  routing_key_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RabbitMQ.BasicProperties.routing_key)
}
inline std::string* BasicProperties::_internal_mutable_routing_key() {
  
  return routing_key_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* BasicProperties::release_routing_key() {
  // @@protoc_insertion_point(field_release:RabbitMQ.BasicProperties.routing_key)
  
  return routing_key_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void BasicProperties::set_allocated_routing_key(std::string* routing_key) {
  if (routing_key != nullptr) {
    
  } else {
    
  }
  routing_key_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), routing_key);
  // @@protoc_insertion_point(field_set_allocated:RabbitMQ.BasicProperties.routing_key)
}

// -------------------------------------------------------------------

// Message_Payload

// .RabbitMQ.BasicProperties properties = 1;
inline bool Message_Payload::_internal_has_properties() const {
  return this != internal_default_instance() && properties_ != nullptr;
}
inline bool Message_Payload::has_properties() const {
  return _internal_has_properties();
}
inline void Message_Payload::clear_properties() {
  if (GetArenaNoVirtual() == nullptr && properties_ != nullptr) {
    delete properties_;
  }
  properties_ = nullptr;
}
inline const ::RabbitMQ::BasicProperties& Message_Payload::_internal_properties() const {
  const ::RabbitMQ::BasicProperties* p = properties_;
  return p != nullptr ? *p : *reinterpret_cast<const ::RabbitMQ::BasicProperties*>(
      &::RabbitMQ::_BasicProperties_default_instance_);
}
inline const ::RabbitMQ::BasicProperties& Message_Payload::properties() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.Message.Payload.properties)
  return _internal_properties();
}
inline ::RabbitMQ::BasicProperties* Message_Payload::release_properties() {
  // @@protoc_insertion_point(field_release:RabbitMQ.Message.Payload.properties)
  
  ::RabbitMQ::BasicProperties* temp = properties_;
  properties_ = nullptr;
  return temp;
}
inline ::RabbitMQ::BasicProperties* Message_Payload::_internal_mutable_properties() {
  
  if (properties_ == nullptr) {
    auto* p = CreateMaybeMessage<::RabbitMQ::BasicProperties>(GetArenaNoVirtual());
    properties_ = p;
  }
  return properties_;
}
inline ::RabbitMQ::BasicProperties* Message_Payload::mutable_properties() {
  // @@protoc_insertion_point(field_mutable:RabbitMQ.Message.Payload.properties)
  return _internal_mutable_properties();
}
inline void Message_Payload::set_allocated_properties(::RabbitMQ::BasicProperties* properties) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete properties_;
  }
  if (properties) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      properties = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, properties, submessage_arena);
    }
    
  } else {
    
  }
  properties_ = properties;
  // @@protoc_insertion_point(field_set_allocated:RabbitMQ.Message.Payload.properties)
}

// string body = 2;
inline void Message_Payload::clear_body() {
  body_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Message_Payload::body() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.Message.Payload.body)
  return _internal_body();
}
inline void Message_Payload::set_body(const std::string& value) {
  _internal_set_body(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.Message.Payload.body)
}
inline std::string* Message_Payload::mutable_body() {
  // @@protoc_insertion_point(field_mutable:RabbitMQ.Message.Payload.body)
  return _internal_mutable_body();
}
inline const std::string& Message_Payload::_internal_body() const {
  return body_.GetNoArena();
}
inline void Message_Payload::_internal_set_body(const std::string& value) {
  
  body_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message_Payload::set_body(std::string&& value) {
  
  body_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RabbitMQ.Message.Payload.body)
}
inline void Message_Payload::set_body(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  body_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RabbitMQ.Message.Payload.body)
}
inline void Message_Payload::set_body(const char* value, size_t size) {
  
  body_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RabbitMQ.Message.Payload.body)
}
inline std::string* Message_Payload::_internal_mutable_body() {
  
  return body_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message_Payload::release_body() {
  // @@protoc_insertion_point(field_release:RabbitMQ.Message.Payload.body)
  
  return body_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message_Payload::set_allocated_body(std::string* body) {
  if (body != nullptr) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:RabbitMQ.Message.Payload.body)
}

// -------------------------------------------------------------------

// Message

// .RabbitMQ.Message.Payload payload = 1;
inline bool Message::_internal_has_payload() const {
  return this != internal_default_instance() && payload_ != nullptr;
}
inline bool Message::has_payload() const {
  return _internal_has_payload();
}
inline void Message::clear_payload() {
  if (GetArenaNoVirtual() == nullptr && payload_ != nullptr) {
    delete payload_;
  }
  payload_ = nullptr;
}
inline const ::RabbitMQ::Message_Payload& Message::_internal_payload() const {
  const ::RabbitMQ::Message_Payload* p = payload_;
  return p != nullptr ? *p : *reinterpret_cast<const ::RabbitMQ::Message_Payload*>(
      &::RabbitMQ::_Message_Payload_default_instance_);
}
inline const ::RabbitMQ::Message_Payload& Message::payload() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.Message.payload)
  return _internal_payload();
}
inline ::RabbitMQ::Message_Payload* Message::release_payload() {
  // @@protoc_insertion_point(field_release:RabbitMQ.Message.payload)
  
  ::RabbitMQ::Message_Payload* temp = payload_;
  payload_ = nullptr;
  return temp;
}
inline ::RabbitMQ::Message_Payload* Message::_internal_mutable_payload() {
  
  if (payload_ == nullptr) {
    auto* p = CreateMaybeMessage<::RabbitMQ::Message_Payload>(GetArenaNoVirtual());
    payload_ = p;
  }
  return payload_;
}
inline ::RabbitMQ::Message_Payload* Message::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:RabbitMQ.Message.payload)
  return _internal_mutable_payload();
}
inline void Message::set_allocated_payload(::RabbitMQ::Message_Payload* payload) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete payload_;
  }
  if (payload) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      payload = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, payload, submessage_arena);
    }
    
  } else {
    
  }
  payload_ = payload;
  // @@protoc_insertion_point(field_set_allocated:RabbitMQ.Message.payload)
}

// uint32 offset = 2;
inline void Message::clear_offset() {
  offset_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::_internal_offset() const {
  return offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::offset() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.Message.offset)
  return _internal_offset();
}
inline void Message::_internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  offset_ = value;
}
inline void Message::set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.Message.offset)
}

// uint32 length = 3;
inline void Message::clear_length() {
  length_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::_internal_length() const {
  return length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::length() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.Message.length)
  return _internal_length();
}
inline void Message::_internal_set_length(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  length_ = value;
}
inline void Message::set_length(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.Message.length)
}

// string valid = 4;
inline void Message::clear_valid() {
  valid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Message::valid() const {
  // @@protoc_insertion_point(field_get:RabbitMQ.Message.valid)
  return _internal_valid();
}
inline void Message::set_valid(const std::string& value) {
  _internal_set_valid(value);
  // @@protoc_insertion_point(field_set:RabbitMQ.Message.valid)
}
inline std::string* Message::mutable_valid() {
  // @@protoc_insertion_point(field_mutable:RabbitMQ.Message.valid)
  return _internal_mutable_valid();
}
inline const std::string& Message::_internal_valid() const {
  return valid_.GetNoArena();
}
inline void Message::_internal_set_valid(const std::string& value) {
  
  valid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void Message::set_valid(std::string&& value) {
  
  valid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RabbitMQ.Message.valid)
}
inline void Message::set_valid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  valid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RabbitMQ.Message.valid)
}
inline void Message::set_valid(const char* value, size_t size) {
  
  valid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RabbitMQ.Message.valid)
}
inline std::string* Message::_internal_mutable_valid() {
  
  return valid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Message::release_valid() {
  // @@protoc_insertion_point(field_release:RabbitMQ.Message.valid)
  
  return valid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_valid(std::string* valid) {
  if (valid != nullptr) {
    
  } else {
    
  }
  valid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), valid);
  // @@protoc_insertion_point(field_set_allocated:RabbitMQ.Message.valid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace RabbitMQ

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RabbitMQ::ExchangeType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RabbitMQ::ExchangeType>() {
  return ::RabbitMQ::ExchangeType_descriptor();
}
template <> struct is_proto_enum< ::RabbitMQ::DeliveryMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RabbitMQ::DeliveryMode>() {
  return ::RabbitMQ::DeliveryMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mq_5fmsg_2eproto
